title: "Lampodharaa store"
url: "https://monsoonmalabar.com/crr"
email: "crajathi7days@gmail.com"
markdown: kramdown
mobile: "916383334678"
country: "India"
currency_code: "INR"
paypal_email: ""
razorpay_key: ""
location: "11.0023956,77.0031483"
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
permalink: /products/:title/
paginate: 10
paginate_path: 'page/:num/'
favicon: "https://monsoonmalabar.com/crr/logo.png"
paypal: 
fb_appid: ""
analytics: 
adsense: 